name: devops-assignment-03
description: Sample python dev application
version: 0.1.0
kubeVersion: ">=1.2.0"
keywords:
  - python
  - devops
  - web
  - inspectorio
home: https://github.com/khoatdd/devops-assignment-03
sources:
  - https://hub.docker.com/r/khoatdd/devops-assignment-03/
maintainers:
  - name: khoatdd
    email: dangkhoa114@gmail.com
