apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "devops-assignment.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostName }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "devops-assignment.fullname" . }}
          servicePort: {{ .Values.service.port }}